---
- name: Install php-fpm and deps 
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-enchant
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-ming
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-snmp
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - php-apc
  notify: restart php5-fpm

- name: Fix CGI PathInfo
  ini_file: dest=/etc/php5/fpm/php.ini section=PHP option=cgi.fix_pathinfo value=0 backup=yes
  notify: restart php5-fpm